"""Retention for final audio generated by gateway auto-TTS.

The files managed here are the exact final artifacts delivered to a messaging
platform or Discord voice channel. Provider-internal scratch files are outside
this contract. Retention is provider- and engine-neutral because every gateway
auto-TTS backend receives an output path from this module.
"""

from __future__ import annotations

import math
import os
import stat
import time
import uuid
from pathlib import Path
from typing import Any, Iterable, Mapping

from hermes_constants import get_hermes_home

DEFAULT_GENERATED_AUDIO_RETENTION_HOURS = 24.0
_GENERATED_AUDIO_PREFIX = "tts_reply_"
_AUDIO_SUFFIXES = frozenset({".flac", ".m4a", ".mp3", ".ogg", ".opus", ".wav"})


def resolve_generated_audio_retention_hours(config: Mapping[str, Any] | None) -> float:
    """Return configured retention hours, failing safely to the 24-hour default."""
    tts = config.get("tts") if isinstance(config, Mapping) else None
    value = tts.get("generated_audio_retention_hours") if isinstance(tts, Mapping) else None
    if value is None:
        return DEFAULT_GENERATED_AUDIO_RETENTION_HOURS
    if isinstance(value, bool):
        return DEFAULT_GENERATED_AUDIO_RETENTION_HOURS
    try:
        hours = float(value)
    except (TypeError, ValueError):
        return DEFAULT_GENERATED_AUDIO_RETENTION_HOURS
    if not math.isfinite(hours) or hours < 0:
        return DEFAULT_GENERATED_AUDIO_RETENTION_HOURS
    return hours


def configured_generated_audio_retention_hours() -> float:
    """Read the current Hermes config so changes apply without a gateway restart."""
    try:
        from hermes_cli.config import load_config

        return resolve_generated_audio_retention_hours(load_config())
    except Exception:
        return DEFAULT_GENERATED_AUDIO_RETENTION_HOURS


def generated_audio_directory(*, hermes_home: Path | None = None) -> Path:
    directory = Path(hermes_home or get_hermes_home()) / "audio" / "generated"
    directory.mkdir(parents=True, exist_ok=True)
    try:
        directory.chmod(0o700)
    except OSError:
        pass
    return directory


def build_generated_audio_path(
    extension: str,
    *,
    hermes_home: Path | None = None,
    now: float | None = None,
) -> Path:
    """Allocate a unique final-audio path without creating the file itself."""
    suffix = extension.lower().lstrip(".")
    if f".{suffix}" not in _AUDIO_SUFFIXES:
        raise ValueError(f"unsupported generated-audio extension: {extension}")
    timestamp = int(time.time() if now is None else now)
    return generated_audio_directory(hermes_home=hermes_home) / (
        f"{_GENERATED_AUDIO_PREFIX}{timestamp}_{uuid.uuid4().hex[:12]}.{suffix}"
    )


def _managed_regular_audio(path: Path, directory: Path) -> bool:
    try:
        info = path.lstat()
    except OSError:
        return False
    if not stat.S_ISREG(info.st_mode):
        return False
    return (
        path.parent == directory
        and path.name.startswith(_GENERATED_AUDIO_PREFIX)
        and path.suffix.lower() in _AUDIO_SUFFIXES
    )


def prune_generated_audio(
    *,
    retention_hours: float,
    hermes_home: Path | None = None,
    now: float | None = None,
    exclude: Iterable[Path | str] = (),
) -> int:
    """Remove expired managed audio files and nothing else."""
    directory = generated_audio_directory(hermes_home=hermes_home)
    current_time = time.time() if now is None else now
    cutoff = current_time - max(0.0, retention_hours) * 3600.0
    excluded = {Path(item).absolute() for item in exclude}
    removed = 0
    try:
        candidates = list(directory.iterdir())
    except OSError:
        return 0
    for path in candidates:
        if path.absolute() in excluded or not _managed_regular_audio(path, directory):
            continue
        try:
            if path.stat().st_mtime > cutoff:
                continue
            path.unlink()
            removed += 1
        except OSError:
            continue
    return removed


def finalize_generated_audio(
    paths: Iterable[Path | str],
    *,
    retention_hours: float | None = None,
    hermes_home: Path | None = None,
    now: float | None = None,
) -> int:
    """Secure delivered artifacts, or delete them when retention is disabled."""
    retained = [Path(item) for item in paths if item]
    hours = (
        configured_generated_audio_retention_hours()
        if retention_hours is None
        else retention_hours
    )
    if hours <= 0:
        removed = 0
        for path in retained:
            try:
                path.unlink()
                removed += 1
            except OSError:
                continue
        return removed
    for path in retained:
        try:
            if path.is_file() and not path.is_symlink():
                path.chmod(0o600)
        except OSError:
            continue
    return prune_generated_audio(
        retention_hours=hours,
        hermes_home=hermes_home,
        now=now,
        exclude=retained,
    )
